# Generated by Django 6.0.4 on 2026-04-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField()),
                ('repo_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overall_health_score', models.FloatField(default=0)),
                ('risk_level', models.CharField(default='unknown', max_length=20)),
                ('total_commits', models.IntegerField(default=0)),
                ('total_files', models.IntegerField(default=0)),
                ('bug_fix_ratio', models.FloatField(default=0)),
                ('avg_complexity', models.FloatField(default=0)),
                ('predicted_failure_probability', models.FloatField(default=0)),
                ('estimated_cost_of_inaction', models.FloatField(default=0)),
                ('file_analysis_json', models.TextField(default='[]')),
                ('ceo_report', models.TextField(default='')),
                ('commit_trend_json', models.TextField(default='[]')),
                ('top_risky_files_json', models.TextField(default='[]')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
